### ISSUE TITLE
按教程安装后报错如下

### ISSUE THREAD

**Issue by peindunk** [Hiject/Hiject#347]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
`Fatal error: Uncaught Error: Class 'SimpleLogger\Logger' not found in C:\nginx-1.20.2\html\jitamin\app\Providers\LoggingServiceProvider.php:37 Stack trace: #0 C:\nginx-1.20.2\html\jitamin\vendor\pimple\pimple\src\Pimple\Container.php(274): Jitamin\Providers\LoggingServiceProvider->register(Object(Pimple\Container)) #1 C:\nginx-1.20.2\html\jitamin\bootstrap\app.php(17): Pimple\Container->register(Object(Jitamin\Providers\LoggingServiceProvider)) #2 C:\nginx-1.20.2\html\jitamin\public\index.php(16): require_once('C:\\nginx-1.20.2...') #3 {main} thrown in C:\nginx-1.20.2\html\jitamin\app\Providers\LoggingServiceProvider.php on line 37`

### Steps To Reproduce:

**Comment by Iceprism** [comment]
我也是这样 你有好的解决方法吗？

**Comment by Nijika0529** [comment]
把composer.json的49行开始的改成这样
```    "autoload" : {
        "classmap" : ["app/"],
        "psr-4" : {
            "Jitamin\\" : "app/",
             "PicoDb\\": "vendor/jitamin/picodb/src/",
             "SimpleLogger\\":"vendor/jitamin/simple-logger/src",
             "JsonRPC\\":"vendor/jitamin/json-rpc/src",
             "SimpleValidator\\":"vendor/jitamin/simple-validator/src"
        },
        "files" : [
            "app/helpers.php"
        ]
    },
```

**Comment by cbxbw** [comment]
> "psr-4" : {
>             "Jitamin\\" : "app/",
>              "PicoDb\\": "vendor/jitamin/picodb/src/",
>              "SimpleLogger\\":"vendor/jitamin/simple-logger/src",
>              "JsonRPC\\":"vendor/jitamin/json-rpc/src",
>              "SimpleValidator\\":"vendor/jitamin/simple-validator/src"
>         },

没用  composer 1.8.7   php 5.6 还是这个报错
